plugin: amazon.aws.aws_ec2

regions:
  - ap-southeast-1

profile: ansible

filters:
  tag:Project:
    - realworld
  tag:Environment:
    - k8s-dev
  instance-state-name:
    - running

hostnames:
  - tag:Name
  - instance-id
  

compose:
  ansible_host: public_ip_address
  ansible_user: '"ubuntu"'
  ansible_ssh_private_key_file: '"/home/devops/.ssh/realworld-project-key-main.pem"'

keyed_groups:
  - key: tags.Environment
    prefix: env

groups:
  control: tags.Role == "control"
  worker: tags.Role == "worker"
  k8s_cluster: tags.Environment == "k8s-dev"