apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: realworld

type: Opaque

stringData:
  DATABASE_URL: postgresql://app:devops2026@postgres:5432/realworld?schema=public
  POSTGRES_PASSWORD: devops2026
  JWT_SECRET: super-secret-jwt-key