apiVersion: v1
kind: ConfigMap

metadata:
  name: backend-config
  namespace: realworld

data:
  NODE_ENV: "production"
  PORT: "3000"
  API_PREFIX: "/api"
  APP_VERSION: "1.0.0"
  LOG_LEVEL: "info"
  TZ: "UTC"