- name: Check if cluster already initialized
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_initialized

- name: Initialize Kubernetes control plane
  command: >
    kubeadm init
    --pod-network-cidr=192.168.0.0/16
  when: not kubeadm_initialized.stat.exists 

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  changed_when: false

- name: Save join command
  copy:
    dest: /etc/kubernetes/kubeadm_join.sh
    mode: "0755"
    content: |
      {{ join_command.stdout | trim }} --cri-socket unix:///run/containerd/containerd.sock

